# can be multiline.
description = '''



'''

# IHC as follows
always_positive_ihc = ['CD20','CD19','CD10','CD25']
always_negative_ihc = ['CD5']
usually_positive_ihc = []
usually_negative_ihc = []

# can be multiline, as strings separated by commas.
differentials = [

]
