# can be multiline.
description = '''



'''

# IHC.
always_positive_ihc = ['cd20','cd19','cd10']
always_negative_ihc = ['CD5','CD25']
usually_positive_ihc = []
usually_negative_ihc = []

# can be multiline, as strings separated by commas.
differentials = [

]
