# can be multiline.
description = '''



'''

# must be in format ihc = ['ihc1','ihc2',etc.]
always_positive_ihc = ['cd20','cd19','cd5','cd23']
always_negative_ihc = []
usually_positive_ihc = []
usually_negative_ihc = []

# can be multiline, as strings separated by commas.
differentials = [

]

