# can be multiline.
description = '''

Small B cell lymphoproliferation affecting the red pulp of the spleen.

'''

# Proportion of all lymphomas (as decimal, with 0.2=20%)
proportion = 0

# must be in format ihc = ['ihc1','ihc2',etc.]
always_positive_ihc = []
always_negative_ihc = []
usually_positive_ihc = []
usually_negative_ihc = []

# can be multiline, as strings separated by commas.
differentials = [

]

# Cytological features (can be multiline)
cytology = [
'villous'
]
