# can be multiline.
description = '''
Small B cell neoplasm that replaces splenic white pulp germinal centres.
The cells extend to peripheral (marginal) larger cells with some blasts.

'''

# Proportion of all lymphomas (as decimal, with 0.2=20%)
proportion = 0

# must be in format ihc = ['ihc1','ihc2',etc.]
always_positive_ihc = ['cd20','cd79a']
always_negative_ihc = ['cd5','cd10','cd23','cd43','cyclin_d1','bcl6']
usually_positive_ihc = []
usually_negative_ihc = []

# can be multiline, as strings separated by commas.
differentials = [

]

