# can be multiline.
description = '''



'''

# Proportion of all lymphomas (as decimal, with 0.2=20%)
proportion = 0

# must be in format ihc = ['ihc1','ihc2',etc.]
always_positive_ihc = ['cd3','cd56']
always_negative_ihc = ['cd4','cd20']
usually_positive_ihc = []
usually_negative_ihc = []

# can be multiline, as strings separated by commas.
differentials = [

]

